### ISSUE TITLE
Cord crashes when I move the window around

### ISSUE THREAD

**Issue by phuketmymac** [dorianj/CoRD#78]
Hi,

This is my 2nd day using Cord and it has been great.
However I am experiencing systematic crashes when I try to move around the window, connected to my Windows 2012 Server and logged in.
Every single time it will crash.

But if I do it without being connected to my server or logged in as a user, it won't.
I couldn't try another Remote Desktop connection other than my Windows 2012 Server...

If you need the crash log, please let me know.
Thank you.

**Comment by Ezerbeth** [comment]
Same problem here. Even quitting CoRD will make it crash.

Used to work fine on Yosemite, not usable on El Capitan.

**Comment by lutnos** [comment]
Hi

I think this is a duplicate of my #75

**Comment by MarshM4ll0w** [comment]
Ditto on the issue.  iMac 5k El Capitan 10.11.4.  Cord Version 0.5.7 (5701)
@lutnos I agree this is a duplicate, but you're issue #75 is closed.  I'm new to github so I assumed that meant a solution was found.  I guess not haha.

**Comment by lutnos** [comment]
I think it is fixed (or at least worked around) in the source, but without a fresh binary release, we need to build it & I haven't myself yet looked at doing that.

**Comment by Ezerbeth** [comment]
I tried compiling the source but getting problems with developer keys and such... Ended up using a competing product instead.

**Comment by jameslbrown** [comment]
Useless on Sierra DP3 - constantly unexpectedly quits. Looks like CoRD is dead and we need to look elsewhere?

**Comment by peelman** [comment]
Yes.

https://github.com/dorianj/CoRD/blob/master/README.md

**Comment by gartha1** [comment]
It still crashes, 2019

Peelman gives a link https://github.com/dorianj/CoRD/blob/master/README.md .  

that says 

"
Deprecation Notice
This project is no longer being maintained as of August 16, 2015.
Please consider using the free official Remote Desktop Client from Microsoft, available on the Mac App Store.
"
